baseURL = "https://marcusilgner.com/"
languageCode = "en-uk"
title = "Marcus Ilgner"
theme = "hugo-coder"
enableEmoji = true

disqusShortname = "marcusilgner"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

canonifyurls = true

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[params]
  author = "Marcus Ilgner"
  info = "Hacker, hiker, gaming geek"
  avatarurl = "images/avatar.jpg"
  # gravatar = "mail@marcusilgner.com"
  enableTwemoji = true

  keywords = "blog,developer,personal"
  rtl = false
  dateformat = "January 2, 2006"
  since = "2018"


  # Custom CSS
  # customCSS = ["custom.css"]
  
  # Custom JS
  customJS = ["scripts/mermaid.min.js", "scripts/init.js"]

[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/milgner/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/milgner/"
[[params.social]]
    name = "Xing"
    icon = "fa fa-xing fa-2x"
    weight = 3
    url = "https://www.xing.com/profile/Marcus_Ilgner"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/marcus-ilgner-32aaa81b2/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 5
    url = "https://twitter.com/LambdaAbstract"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
[[menu.imprint]]
    name = "Imprint"
    weight = 4
    url = "/imprint/"

